name: Frontend Unit Tests

on:
  workflow_call:

jobs:  
  nextjs-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - name: Use npm
        uses: actions/setup-node@v4

      - name: Build frontend
        run: |
          npm install
          npm run test