name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  unit-test-frontend:
    uses: ./.github/workflows/test-frontend.yaml
  build-nextjs:
    uses: ./.github/workflows/build-frontend.yaml
  unit-test-gocert:
    needs: [build-nextjs]
    uses: ./.github/workflows/test-gocert.yaml
  go-vet:
    needs: [build-nextjs]
    uses: ./.github/workflows/go-vet.yaml
  go-lint:
    needs: [build-nextjs]
    uses: ./.github/workflows/go-lint.yaml
  build-gocert:
    needs: [build-nextjs]
    uses: ./.github/workflows/build-gocert.yaml
  rock-build:
    needs: [build-gocert, unit-test-gocert, go-vet, go-lint]
    uses: ./.github/workflows/build-rock.yaml
  rock-scan:
    if: github.ref_name == 'main'
    needs: [rock-build]
    uses: ./.github/workflows/scan-rock.yaml
  publish:
    if: github.ref_name == 'main'
    needs: [rock-build]
    uses: ./.github/workflows/publish-rock.yaml
