name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  unit-test-frontend:
    uses: ./.github/workflows/test-frontend.yaml
  nextjs-build:
    uses: ./.github/workflows/build-frontend.yaml
  go-unit-test:
    needs: [nextjs-build]
    uses: ./.github/workflows/test-notary.yaml
  go-vet:
    needs: [nextjs-build]
    uses: ./.github/workflows/go-vet.yaml
  go-lint:
    needs: [nextjs-build]
    uses: ./.github/workflows/go-lint.yaml
  go-build:
    needs: [nextjs-build]
    uses: ./.github/workflows/build-notary.yaml
  rock-build:
    needs: [go-build, go-unit-test, go-vet, go-lint]
    uses: ./.github/workflows/build-rock.yaml
  rock-scan:
    if: github.ref_name == 'main'
    needs: [rock-build]
    uses: ./.github/workflows/scan-rock.yaml
  rock-publish:
    if: github.ref_name == 'main'
    needs: [rock-build]
    uses: ./.github/workflows/publish-rock.yaml
  snap-build:
    needs: [go-build, go-unit-test, go-vet, go-lint]
    uses: ./.github/workflows/build-snap.yaml
  snap-publish:
    if: github.ref_name == 'main'
    needs: [snap-build]
    uses: ./.github/workflows/publish-snap.yaml
